[package]
name = "raddar_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.103", features = ["full", "extra-traits", "parsing"] }
quote = "1.0"
proc-macro2 = "1.0.47"